program tests

  ! Driver program for FRUIT unit tests in:
  ! test_allocatable_string.F90
  ! test_crop_coefficients__FAO56.F90
  ! test_datetime.F90
  ! test_exceptions__index_values_valid.F90
  ! test_gash.F90
  ! test_kiss.F90
  ! test_timer.F90

  ! Generated by FRUITPy.

  use fruit
  use test_allocatable_string
  use test_crop_coefficients__FAO56
  use test_datetime
  use test_exceptions
  use test__gash
  use test_kiss
  use test_timer

  implicit none

  call init_fruit

  ! test_allocatable_string.F90:
  call run_test_case(test_string_list_with_character,"fstring_list: parse comma-spaced text string into correct number of columns")

  ! test_crop_coefficients__FAO56.F90:
  call setup_crop_coefficients__FAO56
  call run_test_case(test_crop_coefficients_parsing,"crop_coefficients__FAO56: test growth stage table parsing")
  call run_test_case(test_crop_coefficients_basic,"crop_coefficients__FAO56: test crop coefficient interpretation when table vals missing")
  call run_test_case(test_gdd_max_plus_min_simple,"growing_degree_day: calculate simple GDD as compared to Wilson and Barnett (1983) values")

  ! test_datetime.F90:
  call run_test_case(test_datetime_basic_dateparse,"datetime: parse with default mm/dd/yyyy date format")
  call run_test_case(test_datetime_basic_mangled_dateparse,"datetime: parse with default mm/dd/yyyy date format, missing '0' values in month and day")
  call run_test_case(test_datetime_custom_dateparse,"datetime: parse with custom yyyy-mm-dd date format")
  call run_test_case(test_datetime_addition,"datetime: add 5 to Julian day and return the correct Gregorian date")

  ! test_exceptions__index_values_valid.F90:
  call run_test_case(test_check_array_bounds_1d,"test_check_array_bounds_1d")

  ! test_gash.F90:
  call run_test_case(test_gash_psat_calculation,"gash: test calculation of Gash PSat")
  call run_test_case(test_gash_calculation,"gash: calculate Gash interception for published case")

  ! test_kiss.F90:
  call run_test_case(test_kiss_random_number_generator,"kiss_random_number_generator: test for expected value after 1 billion calls")

  ! test_timer.F90:
  call run_test_case(test_timer_basic,"timer: test basic functionality - convert seconds to hms")
  call run_test_case(test_timer_split,"timer: test split and elapsed timer functionality")
  call run_test_case(test_timer_prettyprint,"timer: test ability to output in human-readable form")

  call fruit_summary
  call fruit_finalize

end program tests